spring:
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      host: localhost
      port: 26000
      username: root
      password: root
      database: cqrs

  rabbitmq:
    rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest