spring:
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      host: mongo
      port: 27017
      username: root
      password: root
      database: cqrs

  rabbitmq:
    rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest